apiVersion: v1
kind: Service
metadata:
  name: technitium-metrics-exporter
  labels:
    app.kubernetes.io/name: technitium-metrics-exporter
spec:
  selector:
    app.kubernetes.io/name: technitium-metrics-exporter
  ports:
    - name: metrics
      port: 10053
      targetPort: metrics
